export const ALL_STAFF_REQUEST = "ALL_STAFF_REQUEST";
export const ALL_STAFF_SUCCESS = "ALL_STAFF_SUCCESS";
export const ALL_STAFF_FAIL = "ALL_STAFF_FAIL";

export const ADMIN_STAFF_REQUEST = "ADMIN_STAFF_REQUEST";
export const ADMIN_STAFF_SUCCESS = "ADMIN_STAFF_SUCCESS";
export const ADMIN_STAFF_FAIL = "ADMIN_STAFF_FAIL";

export const NEW_STAFF_REQUEST = "NEW_STAFF_REQUEST";
export const NEW_STAFF_SUCCESS = "NEW_STAFF_SUCCESS";
export const NEW_STAFF_RESET = "NEW_STAFF_RESET";
export const NEW_STAFF_FAIL = "NEW_STAFF_FAIL";

export const UPDATE_STAFF_REQUEST = "UPDATE_STAFF_REQUEST";
export const UPDATE_STAFF_SUCCESS = "UPDATE_STAFF_SUCCESS";
export const UPDATE_STAFF_RESET = "UPDATE_STAFF_RESET";
export const UPDATE_STAFF_FAIL = "UPDATE_STAFF_FAIL";

export const DELETE_STAFF_REQUEST = "DELETE_STAFF_REQUEST";
export const DELETE_STAFF_SUCCESS = "DELETE_STAFF_SUCCESS";
export const DELETE_STAFF_RESET = "DELETE_STAFF_RESET";
export const DELETE_STAFF_FAIL = "DELETE_STAFF_FAIL";

export const STAFF_DETAILS_REQUEST = "STAFF_DETAILS_REQUEST";
export const STAFF_DETAILS_SUCCESS = "STAFF_DETAILS_SUCCESS";
export const STAFF_DETAILS_FAIL = "STAFF_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
